### ISSUE TITLE
Generic "Start" and "Select" buttons

### ISSUE THREAD

**Issue by benwilson34** [mr-breakfast/mrbreakfasts_free_prompts#14]
I'm developing a PC game that supports multiple types of controllers, so I prefer to use generic gamepad prompts for a more consistent experience. Every modern controller has some kind of "Start" and "Select" buttons even if they use different names, so I think it would be useful to have generic prompts for those buttons. Maybe something like this? (just a quick mockup)

<img width="418" alt="image" src="https://github.com/lopopylopy/mrbreakfasts_free_prompts/assets/21367650/b55fbb14-6c71-492a-81cd-782b3e114812">

What do you think?

**Comment by lopopylopy** [comment]
There are a few things I would edit. I can't tell if the curves are symmetric horizontally and vertically, but if they aren't, I would make them symmetric.

I would make the stroke thickness the same as the bumpers and then increase the size of the text. The button shape would essentially look like the corresponding buttons of the Steam Deck.

![image](https://github.com/lopopylopy/mrbreakfasts_free_prompts/assets/65320586/b030b827-f254-4bd0-a5c4-2151a7840a67)
The "Steam" button here uses Poppins Heavy so it looks consistent at a small size. However, I would be fine with the regular Poppins Bold for the buttons you propose.

This is a good idea though! I tried to do all the generics, but I suppose I forgot about select and start. I'd be happy to review a merge request, but if you don't get to it, I'll do it at some point in the future. Thanks!
